const API='https://dreqidkohffwlhjtnexd.supabase.co/functions/v1/aquarismo-pedidos';
const CATALOG=window.AQ_CATALOG||[];
const LOGIN_USERS=[{"username":"loja01","label":"LOJA 01 — LJ01 POLIPET MATRIZ"},{"username":"loja02","label":"LOJA 02 — LJ02 POLI PET SJC 01"},{"username":"loja03","label":"LOJA 03 — LJ03 POLI PET TBT"},{"username":"loja06","label":"LOJA 06 — LJ06 POLIPET JACAREI 01"},{"username":"loja07","label":"LOJA 07 — LJ07 POLI PET SJC 02"},{"username":"loja08","label":"LOJA 08 — LJ08 POLIPET GUARATINGUETA"},{"username":"loja09","label":"LOJA 09 — LJ09 POLIPET CACAPAVA"},{"username":"loja10","label":"LOJA 10 — LJ10 POLIPET TBT2"},{"username":"loja11","label":"LOJA 11 — LJ11 POLIPET SJC3"},{"username":"loja12","label":"LOJA 12 — LJ12 POLIPET PINDA"},{"username":"loja13","label":"LOJA 13 — LJ13 POLIPET JACAREI 02"},{"username":"loja14","label":"LOJA 14 — LJ14 POLIPET ITAQUA"},{"username":"loja15","label":"LOJA 15 — LJ15 POLIPET MAUA"},{"username":"loja16","label":"LOJA 16 — LJ16 POLIPET ATIBAIA"},{"username":"loja17","label":"LOJA 17 — LJ17 POLIPET MOGI 4"},{"username":"loja18","label":"LOJA 18 — LJ18 POLIPET GUARA 2"},{"username":"loja19","label":"LOJA 19 — LJ19 POLIPET HOVET"},{"username":"loja20","label":"LOJA 20 — LJ20 POLIPET TBT 3"},{"username":"loja21","label":"LOJA 21 — LJ 21 POLIPET SJC 4"},{"username":"loja22","label":"LOJA 22 — LJ22 POLI PET CENTRO"},{"username":"douglas","label":"Douglas — Comprador"}];
const TOKEN_KEY='polipet_aquarismo_token_v1';
let token=localStorage.getItem(TOKEN_KEY)||'', state=null, currentUser=null;
let storeFilter='all', storeSearch='', buyerSearch='', buyerStatus='all';
let saveTimers={}, savingCodes=new Set(), storePoll=null, buyerPoll=null, selectedBuyerStore=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(t){const e=$('toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),2600)}
function fmtDate(v){if(!v)return '—';let d=new Date(v+'T12:00:00');return d.toLocaleDateString('pt-BR')}
function fmtDT(v){if(!v)return '—';return new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function category(i){let d=String(i.description||'').toUpperCase();if(d.startsWith('PL.'))return 'Plantas';if(d.includes('CAMARAO')||d.includes('CAMARÃO')||d.includes('CARAMUJO'))return 'Invertebrados';if(d.startsWith('PX')||d.startsWith('PEIXE'))return 'Peixes';if(/AQUARIO|AQUÁRIO|BETEIRA|PEDRA|TRONCO|ENF\.|OVERFLOW/.test(d))return 'Aquários e decoração';return 'Outros'}
function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
async function api(action,payload={},noAuth=false){let headers={'Content-Type':'application/json'};if(token&&!noAuth)headers.Authorization='Bearer '+token;let r=await fetch(API,{method:'POST',headers,body:JSON.stringify({action,...payload})});let j=await r.json().catch(()=>({error:'Resposta inválida do servidor'}));if(!r.ok){let e=new Error(j.error||('Erro '+r.status));e.status=r.status;e.body=j;throw e} return j}
function initLogin(){let stores=LOGIN_USERS.filter(x=>x.username!=='douglas'),buyer=LOGIN_USERS.find(x=>x.username==='douglas');$('loginUser').innerHTML='<option value="">Selecione...</option><optgroup label="Lojas">'+stores.map(x=>`<option value="${esc(x.username)}">${esc(x.label)}</option>`).join('')+'</optgroup><optgroup label="Comprador"><option value="douglas">'+esc(buyer.label)+'</option></optgroup>'}
async function login(e){e.preventDefault();$('loginError').textContent='';try{let j=await api('login',{username:$('loginUser').value,password:$('loginPassword').value},true);token=j.token;localStorage.setItem(TOKEN_KEY,token);currentUser=j.user;if(j.user.must_change_password){$('passwordModal').classList.remove('hidden');return}await boot()}catch(err){$('loginError').textContent=err.message}}
async function changePassword(e){e.preventDefault();let a=$('newPassword').value,b=$('confirmPassword').value;$('passwordError').textContent='';if(a.length<6){$('passwordError').textContent='Use pelo menos 6 caracteres.';return}if(a!==b){$('passwordError').textContent='As senhas não coincidem.';return}try{await api('change_password',{new_password:a});$('passwordModal').classList.add('hidden');$('newPassword').value=$('confirmPassword').value='';await boot();toast('Senha alterada.')}catch(err){$('passwordError').textContent=err.message}}
function logout(){localStorage.removeItem(TOKEN_KEY);token='';state=null;currentUser=null;clearInterval(storePoll);clearInterval(buyerPoll);$('app').classList.add('hidden');$('loginScreen').classList.remove('hidden');$('loginPassword').value=''}
async function boot(){try{let j=await api('bootstrap');state=j;currentUser=j.user;$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');$('passwordModal').classList.add('hidden');$('userChip').textContent=currentUser.display_name;$('cycleTop').textContent=`${j.cycle.name} • ${fmtDate(j.cycle.starts_on)} → ${fmtDate(j.cycle.ends_on)}`;clearInterval(storePoll);clearInterval(buyerPoll);if(currentUser.role==='store'){renderStore();storePoll=setInterval(checkStoreCycle,60000)}else{renderBuyer();buyerPoll=setInterval(refreshBuyer,10000)}}catch(err){if(err.status===428||err.body?.must_change_password){$('passwordModal').classList.remove('hidden');return}if(err.status===401){logout();return}toast(err.message)}}
async function checkStoreCycle(){if(savingCodes.size)return;try{let j=await api('bootstrap');if(j.cycle.id!==state.cycle.id){state=j;renderStore();toast('Nova semana de pedidos iniciada.')}else{state.status=j.status}}catch(e){}}
function storeTotals(){let q=state.quantities||{},items=0,units=0;for(let v of Object.values(q)){v=Number(v)||0;if(v>0){items++;units+=v}}return {items,units}}
function renderStore(){let t=storeTotals(),processed=state.status?.processed;$('mainContent').innerHTML=`<section class="hero"><div><div class="eyebrow">${esc(state.store.code)} • ${esc(state.store.city||'')}</div><h2>${esc(state.store.name)}</h2><p>Selecione os itens da semana e informe as quantidades. Não é necessário enviar planilha ou clicar em salvar.</p></div><div class="hero-stats"><div class="hero-stat"><b id="sumItems">${t.items}</b><span>Itens</span></div><div class="hero-stat"><b id="sumUnits">${t.units}</b><span>Unidades</span></div><div class="hero-stat"><b>${processed?'OK':'AUTO'}</b><span>${processed?'Lançado':'Salvamento'}</span></div></div></section><div class="toolbar"><div class="search"><span class="search-icon">⌕</span><input id="storeSearch" placeholder="Buscar por item ou código..." value="${esc(storeSearch)}"></div><div class="chips" id="chips">${['all','order','Peixes','Plantas','Invertebrados','Aquários e decoração','Outros'].map(x=>`<button class="chip ${storeFilter===x?'active':''}" data-filter="${esc(x)}">${x==='all'?'Todos':x==='order'?'Meu pedido':esc(x)}</button>`).join('')}</div></div><section class="catalog-panel"><div class="panel-head"><h3>Itens disponíveis</h3><span><span class="autosave"><i class="dot"></i> Salvamento automático</span></span></div><div id="itemList" class="item-list"></div></section>`;$('storeSearch').addEventListener('input',e=>{storeSearch=e.target.value;renderStoreItems()});$('chips').addEventListener('click',e=>{let b=e.target.closest('[data-filter]');if(!b)return;storeFilter=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===storeFilter));renderStoreItems()});renderStoreItems()}
function visibleCatalog(){let q=normalize(storeSearch),quant=state.quantities||{};return CATALOG.filter(i=>{let cat=category(i),okFilter=storeFilter==='all'||(storeFilter==='order'&&Number(quant[i.code]||0)>0)||storeFilter===cat;let okQ=!q||normalize(`${i.code} ${i.description}`).includes(q);return okFilter&&okQ})}
function renderStoreItems(){let list=visibleCatalog(),q=state.quantities||{},el=$('itemList');if(!el)return;if(!list.length){el.innerHTML='<div class="empty">Nenhum item encontrado.</div>';return}el.innerHTML=list.map(i=>{let qty=Number(q[i.code]||0),cat=category(i);return `<div class="item-row ${qty>0?'ordered':''}" data-row="${i.code}"><div><div class="item-code">CÓD. ${esc(i.code)}</div><div class="item-name">${esc(i.description)}</div><div class="item-meta"><span class="cat-badge">${esc(cat)}</span></div></div><div class="qty-area"><label class="qty-label">Quantidade</label><input class="qty-input" data-qty="${i.code}" type="number" inputmode="numeric" min="0" max="99999" step="1" value="${qty||''}" placeholder="0"><div class="save-state" id="save-${i.code}"></div></div></div>`}).join('');el.querySelectorAll('[data-qty]').forEach(inp=>{inp.addEventListener('input',onQtyInput);inp.addEventListener('change',onQtyChange)})}
function onQtyInput(e){let code=e.target.dataset.qty,qty=Math.max(0,Math.floor(Number(e.target.value)||0));state.quantities[code]=qty;if(qty===0)delete state.quantities[code];let row=e.target.closest('.item-row');row?.classList.toggle('ordered',qty>0);updateStoreTotals();let s=$('save-'+code);if(s)s.textContent='Aguardando...';clearTimeout(saveTimers[code]);saveTimers[code]=setTimeout(()=>saveQuantity(code,qty),500)}
function onQtyChange(e){let code=e.target.dataset.qty,qty=Math.max(0,Math.floor(Number(e.target.value)||0));clearTimeout(saveTimers[code]);saveQuantity(code,qty)}
function updateStoreTotals(){let t=storeTotals();if($('sumItems'))$('sumItems').textContent=t.items;if($('sumUnits'))$('sumUnits').textContent=t.units}
async function saveQuantity(code,qty){let i=CATALOG.find(x=>x.code===code);if(!i)return;savingCodes.add(code);let s=$('save-'+code);if(s)s.textContent='Salvando...';try{await api('save_quantity',{code:i.code,description:i.description,quantity:qty});state.status.processed=false;if(s)s.textContent='Salvo';if(storeFilter==='order'&&qty===0)setTimeout(renderStoreItems,250)}catch(err){if(s)s.textContent='Erro';toast(err.message)}finally{savingCodes.delete(code)}}
async function refreshBuyer(){try{let j=await api('bootstrap');state=j;renderBuyer(false);if(selectedBuyerStore)await openBuyerStore(selectedBuyerStore,true)}catch(e){}}
function buyerKpis(){let ss=state.stores||[],withOrder=ss.filter(x=>x.summary.item_count>0).length,done=ss.filter(x=>x.summary.processed).length;return {all:ss.length,withOrder,empty:ss.length-withOrder,done}}
function renderBuyer(reset=true){let k=buyerKpis();$('mainContent').innerHTML=`<section class="hero"><div><div class="eyebrow">Comprador • Douglas</div><h2>Painel de pedidos das lojas</h2><p>Os pedidos aparecem em tempo real conforme cada unidade informa suas quantidades.</p></div><div class="hero-stats"><button class="btn" id="newCycleBtn">Iniciar nova semana</button></div></section><section class="dashboard-grid"><div class="kpi"><span>Lojas</span><b>${k.all}</b></div><div class="kpi"><span>Com pedido</span><b>${k.withOrder}</b></div><div class="kpi"><span>Sem pedido</span><b>${k.empty}</b></div><div class="kpi"><span>Já lançados</span><b>${k.done}</b></div></section><div class="toolbar"><div class="search"><span class="search-icon">⌕</span><input id="buyerSearch" placeholder="Buscar loja ou cidade..." value="${esc(buyerSearch)}"></div><select id="buyerStatus" class="select" style="width:auto;min-width:180px"><option value="all">Todos os status</option><option value="with">Com pedido</option><option value="empty">Sem pedido</option><option value="done">Lançados</option><option value="pending">Pendentes de lançamento</option></select></div><div id="storeGrid" class="store-grid"></div>`;$('buyerStatus').value=buyerStatus;$('buyerSearch').addEventListener('input',e=>{buyerSearch=e.target.value;renderBuyerCards()});$('buyerStatus').addEventListener('change',e=>{buyerStatus=e.target.value;renderBuyerCards()});$('newCycleBtn').onclick=openCycleModal;renderBuyerCards()}
function renderBuyerCards(){let el=$('storeGrid');if(!el)return;let q=normalize(buyerSearch),ss=(state.stores||[]).filter(s=>{let sm=s.summary||{},match=!q||normalize(`${s.code} ${s.name} ${s.city}`).includes(q),status=buyerStatus==='all'||(buyerStatus==='with'&&sm.item_count>0)||(buyerStatus==='empty'&&sm.item_count===0)||(buyerStatus==='done'&&sm.processed)||(buyerStatus==='pending'&&sm.item_count>0&&!sm.processed);return match&&status});el.innerHTML=ss.map(s=>{let sm=s.summary||{},cls=sm.processed?'done':sm.item_count>0?'open':'empty',label=sm.processed?'Lançado':sm.item_count>0?'Com pedido':'Sem pedido';return `<article class="store-card" data-store="${s.id}"><div class="store-top"><div><div class="store-code">${esc(s.code)}</div><div class="store-name">${esc(s.name)}</div><div class="store-city">${esc(s.city||'')} • ${esc(s.neighborhood||'')}</div></div><span class="status ${cls}">${label}</span></div><div class="store-stats"><div class="store-stat"><span>Itens</span><b>${sm.item_count||0}</b></div><div class="store-stat"><span>Unidades</span><b>${sm.total_units||0}</b></div></div><div class="last-update">${sm.last_activity_at?'Última alteração: '+fmtDT(sm.last_activity_at):'Nenhuma quantidade informada ainda'}</div></article>`}).join('')||'<div class="empty" style="grid-column:1/-1">Nenhuma loja encontrada.</div>';el.querySelectorAll('[data-store]').forEach(x=>x.onclick=()=>openBuyerStore(x.dataset.store))}
async function openBuyerStore(id,silent=false){selectedBuyerStore=id;try{let j=await api('store_order',{store_id:id}),sum=j.items.reduce((a,x)=>a+Number(x.quantity||0),0),processed=j.status.processed;let back=$('storeSheet');back.classList.remove('hidden');back.innerHTML=`<div class="side-sheet" onclick="event.stopPropagation()"><div class="sheet-head"><div><div class="store-code">${esc(j.store.code)}</div><h3>${esc(j.store.name)}</h3><p>${j.items.length} item(ns) • ${sum} unidade(s) • ${j.status.last_activity_at?'Atualizado '+fmtDT(j.status.last_activity_at):'Sem movimentação'}</p></div><div class="sheet-actions"><button class="btn" id="copyOrder">Copiar pedido</button><button class="btn" id="csvOrder">Baixar CSV</button><button class="btn ${processed?'warning':'success'}" id="processOrder">${processed?'Reabrir':'Marcar como lançado'}</button><button class="btn" id="closeSheet">Fechar</button></div></div><div class="sheet-body">${j.items.length?`<table class="order-table"><thead><tr><th>Código</th><th>Item</th><th>GTIN</th><th>Qtd.</th></tr></thead><tbody>${j.items.map(i=>`<tr><td><b>${esc(i.code)}</b></td><td>${esc(i.description)}</td><td>${esc(i.gtin||'—')}</td><td class="qty">${i.quantity}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Esta loja ainda não informou itens nesta semana.</div>'}</div></div>`;back.onclick=closeBuyerSheet;$('closeSheet').onclick=closeBuyerSheet;$('copyOrder').onclick=()=>copyOrder(j);$('csvOrder').onclick=()=>downloadOrderCsv(j);$('processOrder').onclick=async()=>{try{await api('set_processed',{store_id:id,value:!processed});toast(!processed?'Pedido marcado como lançado.':'Pedido reaberto.');closeBuyerSheet();let b=await api('bootstrap');state=b;renderBuyer()}catch(e){toast(e.message)}}}catch(e){if(!silent)toast(e.message)}}
function closeBuyerSheet(){$('storeSheet').classList.add('hidden');$('storeSheet').innerHTML='';selectedBuyerStore=null}
async function copyOrder(j){let text=['CODIGO\tITEM\tQUANTIDADE',...j.items.map(i=>`${i.code}\t${i.description}\t${i.quantity}`)].join('\n');try{await navigator.clipboard.writeText(text);toast('Pedido copiado.')}catch(e){toast('Não foi possível copiar.')}}
function downloadOrderCsv(j){let lines=['CODIGO;ITEM;GTIN;QUANTIDADE',...j.items.map(i=>`${i.code};"${String(i.description).replace(/"/g,'""')}";${i.gtin||''};${i.quantity}`)],blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Aquarismo_${j.store.code.replace(/\s/g,'_')}_${state.cycle.starts_on}.csv`;a.click();URL.revokeObjectURL(a.href)}
function openCycleModal(){let cur=new Date(state.cycle.ends_on+'T12:00:00'),start=new Date(cur);start.setDate(cur.getDate()+1);let end=new Date(start);end.setDate(start.getDate()+6),f=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;$('cycleModal').classList.remove('hidden');$('cycleModal').innerHTML=`<div class="modal"><h3>Iniciar nova semana</h3><p>Os pedidos atuais serão preservados no histórico e as 20 lojas começarão uma nova rodada zerada.</p><form id="cycleForm"><div class="field"><label>Início</label><input id="cycleStart" class="input" type="date" value="${f(start)}" required></div><div class="field"><label>Fim</label><input id="cycleEnd" class="input" type="date" value="${f(end)}" required></div><div class="modal-actions"><button class="btn" type="button" id="cancelCycle">Cancelar</button><button class="btn primary" type="submit">Iniciar semana</button></div></form></div>`;$('cancelCycle').onclick=()=>$('cycleModal').classList.add('hidden');$('cycleForm').onsubmit=createCycle}
async function createCycle(e){e.preventDefault();if(!confirm('Iniciar uma nova semana de pedidos?'))return;try{let s=$('cycleStart').value,en=$('cycleEnd').value;await api('new_cycle',{starts_on:s,ends_on:en,name:`Semana ${new Date(s+'T12:00:00').toLocaleDateString('pt-BR')} a ${new Date(en+'T12:00:00').toLocaleDateString('pt-BR')}`});$('cycleModal').classList.add('hidden');let j=await api('bootstrap');state=j;$('cycleTop').textContent=`${j.cycle.name} • ${fmtDate(j.cycle.starts_on)} → ${fmtDate(j.cycle.ends_on)}`;renderBuyer();toast('Nova semana iniciada.')}catch(e){toast(e.message)}}
$('loginForm').addEventListener('submit',login);$('passwordForm').addEventListener('submit',changePassword);$('logoutBtn').addEventListener('click',async()=>{try{await api('logout')}catch(e){}logout()});
initLogin();if(token)boot();
